### ISSUE TITLE
AttributeError raised when AWS_ENABLE_HTTP_LOADER not defined

### ISSUE THREAD

**Issue by rhoberman** [willtrking/thumbor_aws#18]
The code handling the new AWS_ENABLE_HTTP_LOADER property falls over if the property is not defined.  Also, this property doesn't seem to be documented in the README.  Ideally this would default to False if not defined.

### Workaround:
Add AWS_ENABLE_HTTP_LOADER=False to the Thumbor config

### Stacktrace:
```
2015-01-29 18:12:47 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1320, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/lib64/python2.6/site-packages/tornado/web.py", line 1503, in wrapper
    result = method(self, *args, **kwargs)
  File "/usr/lib64/python2.6/site-packages/thumbor/handlers/imaging.py", line 100, in get
    self.check_image(kw)
  File "/usr/lib64/python2.6/site-packages/thumbor/handlers/imaging.py", line 96, in check_image
    return self.execute_image_operations()
  File "/usr/lib64/python2.6/site-packages/thumbor/handlers/__init__.py", line 89, in execute_image_operations
    self.filters_runner.apply_filters(thumbor.filters.PHASE_PRE_LOAD, self.get_image)
  File "/usr/lib64/python2.6/site-packages/thumbor/filters/__init__.py", line 81, in apply_filters
    callback()
  File "/usr/lib64/python2.6/site-packages/thumbor/handlers/__init__.py", line 114, in get_image
    self._fetch(self.context.request.image_url, self.context.request.extension, callback)
  File "/usr/lib64/python2.6/site-packages/thumbor/handlers/__init__.py", line 377, in _fetch
    self.context.modules.loader.load(self.context, url, handle_loader_loaded)
  File "/usr/lib/python2.6/site-packages/thumbor_aws-1-py2.6.egg/thumbor_aws/loaders/s3_loader.py", line 34, in load
    if (context.config.AWS_ENABLE_HTTP_LOADER and
  File "/usr/lib/python2.6/site-packages/derpconf/config.py", line 200, in __getattr__
    raise AttributeError(name)
AttributeError: AWS_ENABLE_HTTP_LOADER
```

**Comment by willtrking** [comment]
Thanks for catching this.

Closed with https://github.com/willtrking/thumbor_aws/commit/46aa1ab48749fc2336cd87fdd506ccbc643997eb
