### ISSUE TITLE
socket.error: [Errno 98] Address already in use. When I set multiple buckets.

### ISSUE THREAD

**Issue by fluke** [willtrking/thumbor_aws#19]
```
socket.error: [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/bin/thumbor", line 9, in <module>
    load_entry_point('thumbor==4.10.0', 'console_scripts', 'thumbor')()
  File "/usr/lib64/python2.6/site-packages/thumbor/server.py", line 90, in main
    server.bind(context.server.port, context.server.ip)
  File "/usr/lib64/python2.6/site-packages/tornado/tcpserver.py", line 162, in bind
    backlog=backlog)
  File "/usr/lib64/python2.6/site-packages/tornado/netutil.py", line 104, in bind_sockets
    sock.bind(sockaddr)
  File "<string>", line 1, in bind
```

**Comment by fluke** [comment]
I've set buckets with S3_ALLOWED_BUCKETS. But I keep getting 500: Internal Server Error.

**Comment by willtrking** [comment]
Is this happening when using the botornado pull request?

**Comment by fluke** [comment]
No I'm using the standard master.

**Comment by kartikluke** [comment]
Hello!
Your friend Kartik S. recently e-filed taxes on ClearTax -- and wants to recommend ClearTax to you for your tax return filing.

I'll give you a little bit of context on ClearTax: India's largest tax platform with over a million Indian tax payers and 20,000 businesses. E-Filing is secure and free on our platform.

    - If you receive a Form-16, just upload it here - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcR24ys7x1NWckXwxb-2B1pF95mypUUmKTsTFnYanG6nKh669RppV-2B1QqKrNS5YMtNGu-2FUwTNyZc-2FhvvK9gKLL-2BgmEkViR1yKFLcYoAYJ1uQa9TFfvhoBndhDnmBcbVPcjj59yOzy6fg4Ibmqg1a1ylxtF9ZwW1QWVI6Feloy7M4hfGOXlJNV4TCOVMpy0WK4TgOyOCv0IqxwXoUW0k4QXBLsyGQ6lVnogSPaj8FT68E9GAAnhd40FwTcOi1whI9X9cWN2nNlLU9FzSRJkz68gLu9e04Es-2F4utTsTx3MYjKqvGhSXcMrAwchxYIzocAAss-2BEbmNzgJIv74IgwWlpEgR3qgFJfQ9bXD-2FcFZm3cpZln7u and automatically all details will be filled for you.
    - We support all income types from Indian residents, NRIs, Freelancers and Businesses.
    - We partner with large corporations, public banks and state Governments for customers and employees.

We would love to help you with your e-Filing. Here's the invitation referral link - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcR24ys7x1NWckXwxb-2B1pF95mypUUmKTsTFnYanG6nKh669RppV-2B1QqKrNS5YMtNGu-2FUwTNyZc-2FhvvK9gKLL-2BgmEkViR1yKFLcYoAYJ1uQa9TFfvhoBndhDnmBcbVPcjj59yOzy6fg4Ibmqg1a1ylxtF9ZwW1QWVI6Feloy7M4hfGGggG1kVOi3CbxpCXbuLSlT3Hjefeo0YgwkTiumpvOJFbdDfe58EG-2FXixc4q6rMD7AtXORuctwA8xKUfgApKbgzZI1gc-2BwzJv2j1h9ZJ-2Fj-2B-2BgpWI-2FKVG3m2wIBMF2aqe8IGoV2S5ecp9v6d0SM-2FapVnQUT3Jv4CBh0XS7IS1pQjw-2BCHNkOAoyo0M1cseynGkE

Best,
Neha, Head Customer support, ClearTax

PS: Economic Times and NDTV ranked ClearTax as the best tax platform in India.

**Comment by kartikluke** [comment]
Hello!
Your friend Kartik S. recently e-filed taxes on ClearTax -- and wants to recommend ClearTax to you for your tax return filing.

I'll give you a little bit of context on ClearTax: India's largest tax platform with over a million Indian tax payers and 20,000 businesses. E-Filing is secure and free on our platform.

    - If you receive a Form-16, just upload it here - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcR24ys7x1NWckXwxb-2B1pF95mypUUmKTsTFnYanG6nKh669RppV-2B1QqKrNS5YMtNGu-2FUwTNyZc-2FhvvK9gKLL-2BgmEkViR1yKFLcYoAYJ1uQa9TFfvhoBndhDnmBcbVPcjj594Mt5G-2Bof95m7kpd0zoTv9o2WzaAXzH8g0-2BAPfuJISZMkGocNDJhlFoFy2vPlmnqMAI878REt6n-2Fnr4B0P-2F05r0FEqIXQD6yhHoDepNn1SmPSuy7mza-2B-2FUuu6-2BNVdeAPdGKOhWQ9feNw5LXxpOx31AW-2BRVFBKtDSyCv-2FirdkptoNLUBw-2BkFtcUfnymcvnM-2FSBoRV-2BlQFKVEFe8iDKOGELEFBLIpyAVz5B8Ejun8WENz and automatically all details will be filled for you.
    - We support all income types from Indian residents, NRIs, Freelancers and Businesses.
    - We partner with large corporations, public banks and state Governments for customers and employees.

We would love to help you with your e-Filing. Here's the invitation referral link - http://email.cleartax.in/wf/click?upn=2383OvSW-2BdRJaftD-2Fy6Xl4MKZ1XcRgbuXx-2BnXHXEwpFFiXIumsC59z1sCf1l0Ksq_s5UH8bhnBaopYjthcNSRcR24ys7x1NWckXwxb-2B1pF95mypUUmKTsTFnYanG6nKh669RppV-2B1QqKrNS5YMtNGu-2FUwTNyZc-2FhvvK9gKLL-2BgmEkViR1yKFLcYoAYJ1uQa9TFfvhoBndhDnmBcbVPcjj594Mt5G-2Bof95m7kpd0zoTv9o2WzaAXzH8g0-2BAPfuJISZMqhswWavTo0nZPMSpF8BW4odHh-2FueYX-2BdPDi0Lve4f1u3-2BQdJ7DdMLHetEKFmbeOgGL6Cqv9pylnMz80W38TEqNM9SSfWwSG1NkwGwnFfXlAPsKB4npJz7h7Q0xWHb-2BGTSC78H-2FitApEORPI1EZuqk91qHR8AM3dzxbZnl5k1ysdD2Jx-2B012doiBp-2Fv3gDlz

Best,
Neha, Head Customer support, ClearTax

PS: Economic Times and NDTV ranked ClearTax as the best tax platform in India.
