### ISSUE TITLE
Production Environment

### ISSUE THREAD

**Issue by f00bar** [willtrking/thumbor_aws#2]
Hello,

Has this module been used successfully in a production environment?

Also I'm having some issues with safe (signed) URLs. Here's the debug log:

Wed, 18 Sep 2013 14:42:10 GMT
/thumbor/thumbor/storage/a7f21387d6cefb109f67822411f7263792878e2e
2013-09-18 09:42:10 thumbor:ERROR ERROR: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1055, in _stack_context_handle_exception
    raise_exc_info((type, value, traceback))
  File "/usr/lib/python2.6/site-packages/tornado/web.py", line 1178, in wrapper
    result = method(self, _args, *_kwargs)
  File "/usr/lib64/python2.6/site-packages/thumbor/handlers/imaging.py", line 92, in get
    return self.execute_image_operations()
  File "/usr/lib64/python2.6/site-packages/thumbor/handlers/__init__.py", line 63, in execute_image_operations
    result = self.context.modules.result_storage.get()
  File "/usr/lib64/python2.6/site-packages/thumbor/utils.py", line 33, in wrapper
    return fn(_args, *_kwargs)
TypeError: get() takes exactly 2 arguments (1 given)

2013-09-18 09:42:10 tornado.access:ERROR 500 GET /Ko58RlIHR72cOpQfXkp1KukyafU=/50x50/smart/http%3A%2F%2Fthumbor.policymic.com%3A8888%2Fimage%2Feef304fa724c484a88620a4595460bf7%2Fimage.jpg (98.116.242.17) 25.15ms

Note that signed requests were working as expected prior to switching to the S3 storage engine.

Thanks

**Comment by jeremyjackson89** [comment]
What were the issues? I can run thumbor locally with thumbor_aws just fine, but once I run thumbor on my server and test it out on my local environment it's not pulling in newly uploaded images.

For clarification:

1) I can run thumbor with localhost:8888/params/file.jpg, I can upload a new file to my s3 bucket, refresh the page, and the new image shows just fine.

2) If I switch to my-thumbor.com:8888/params/newFile.jpg, I can upload a new file to my s3 bucket, refresh the page, but it never loads the image. I can open chrome dev tools, go to the "network" tab, and it shows a GET request that never leaves (pending). I can however, switch back to localhost:8888, refresh, and it'll pull the image in. If I switch back to my-thumbor.com:8888 after doing that, it will load the image.

Edit: I stopped running thumbor with my-thumbor.com:8888. and I wind up with this error when the new image fails to load:

```
 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 810, in run
    yielded = self.gen.throw(*sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/handlers/__init__.py", line 106, in get_image
    self.context.request.extension
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
    value = future.result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
    raise_exc_info(self._exc_info)
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 812, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/dist-packages/thumbor-5.0.0rc2-py2.7.egg/thumbor/handlers/__init__.py", line 385, in _fetch
    buffer = yield self.context.modules.loader.load(self.context, url)
TypeError: load() takes exactly 3 arguments (2 given)
```
